# Basic
name:               "蔡涵镛"

author:
  twitter:          chanyying
  github:           chanyying
  email:            caihanyong@foxmail.com

copyright:
  year:             2017
  name:             caihanyong

# Google-analytics
google-analytics:
  id:               "UA-101241731-1"

# URL
url:                "caihanyong.me" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "http://caihanyong.me" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/chanyying"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
theme: jekyll-theme-minimal